apiVersion: v1	
data:	
  userData: DATA	
kind: Secret	
metadata:	
  name: metal3-node01-user-data	
  namespace: metal3	
type: Opaque	
---	
apiVersion: "cluster.k8s.io/v1alpha1"	
kind: Machine	
metadata:	
  name: metal3-node01	
  namespace: metal3
  generateName: baremetal-machine-	
spec:	
  providerSpec:	
    value:	
      apiVersion: "baremetal.cluster.k8s.io/v1alpha1"	
      kind: "BareMetalMachineProviderSpec"	
      image:	
        url: http://172.22.0.1/images/CentOS-7-x86_64-GenericCloud-1901.qcow2	
        checksum: http://172.22.0.1/images/CentOS-7-x86_64-GenericCloud-1901.qcow2.md5sum	
      userData:	
        name: metal3-node01-user-data	
        namespace: metal3
